### ISSUE TITLE
Some ideas about partial lists

### ISSUE THREAD

**Issue by qweeze** [samuelcolvin/dirty-equals#10]
Hi @samuelcolvin

This looks really exciting, I think a library like this should have been created a long time ago :slightly_smiling_face: 

Some time ago I played around with similar idea of partial data equality checks to simplify test assertions and wrote a small [library](https://github.com/qweeze/matchlib) for this.
I just wanted to share a couple of thoughts that you might find interesting. (Or maybe you already considered this, in that case - sorry for bothering)

In my experience a very common and annoying problem is when you need to ensure that a list contains all expected elements but their order is unknown and you don't care about order anyway. When elements are not hashable and not comparable you can't just sort two lists or turn them into sets. For example:
```python
expected_result = [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}]
assert result == expected_result # can't just do that
```
Possible workaround might be something like this:
```python
sorted(result, key=itemgetter("id")) == sorted(expected_result, key=itemgetter("id"))
```
Or perhaps a helper function:
```python
def unordered_equals(first: list, second: list) -> bool:
    return all(el in second for el in first) and all(el in first for el in second)
```
I think it would be great to have a simple way for doing such checks.

Also, sometimes I need to check only specific element(s) in a collection. I often notice that I want to be able to do something like this:
```python
[1, 2, 3] == StartsWith([1, 2])
[1, 2, 3] == Contains(3)

# We only need to check that a user has a post with id=42
response == IsPartialDict({
    "username": "John",
    "posts": Contains(IsPartialDict(id=42)),
})
```

**Comment by samuelcolvin** [comment]
Thanks.

This is all possible already with `IsList`, I just need to write the docs. I'll add more detail with examples tomorrow when I'm at my desk.

**Comment by samuelcolvin** [comment]
This is mostly done, see the docs [here](https://dirty-equals.helpmanual.io/types/#dirty_equals.IsListOrTuple).

I guess we could add `Contains(foobar)` as a more readable alias of `IsListOrTuple(foobar, check_order=False, Length=(0, ...))`.

let me know what you think of the implementation I've used.

**Comment by samuelcolvin** [comment]
`Contains` has been added.
