### ISSUE TITLE
Maintenance status of dirty_equals?

### ISSUE THREAD

**Issue by soxofaan** [samuelcolvin/dirty-equals#100]
Hi,

We started depending on dirty_equals in a couple of test suites instead of further complicating a bunch of ad-hoc, homegrown hacks.
However I noticed there hasn't been activity on this repo since November last year, so I want to kindly check on the maintenance status of this project. 
Just to be sure we're not betting on the wrong horse (including contributing back).

**Comment by samuelcolvin** [comment]
Hi, sorry for the slow response.

We heavily use dirty-equals at Pydantic, it's definitely not unmaintained.

It hasn't received recent commits because for the most part it just works.

**Comment by logi** [comment]
Very good. Hopefully we'll get around to porting over the few matchers that we've implemented beyond yours and raise a PR.

**Comment by samuelcolvin** [comment]
[v0.8.0](https://github.com/samuelcolvin/dirty-equals/releases/tag/v0.8.0) released.
