### ISSUE TITLE
pytz version requirement

### ISSUE THREAD

**Issue by silas** [samuelcolvin/dirty-equals#30]
Is there a reason that dirty-equals requires a semver version of `pytz` or would you be happy to accept a PR to change the requirement to `*`?

I assume it was just added with `poetry add` or something.

**Comment by samuelcolvin** [comment]
Happy to relax the requirement. I just chose the most recent version out of habit.

**Comment by Uninen** [comment]
I just had to drop dirty-equals out of a project because I couldn't get it installed w/ some of the other reqs that got updated. Would be nice to see the PR merged!

Also, Thank You for the project -- it's really nice 👍
