### ISSUE TITLE
Wrong version number in releases

### ISSUE THREAD

**Issue by mgorny** [samuelcolvin/dirty-equals#35]
The pyproject.toml file states:

```
version = "0"
```

for all current releases. This is going to break version requirements in other packages.

**Comment by samuelcolvin** [comment]
The version is set correctly on release.

https://github.com/samuelcolvin/dirty-equals/blob/f6e0d13b14bcfeebbfb0f1b46af9ede8a50d6043/.github/workflows/ci.yml#L129

I don't believe that version number is used anywhere.

**Comment by samuelcolvin** [comment]
I assume `pyproject.toml` doesn't get distributed, so this version value is ignored.

Am I won't somehow?

TBH this is the only project I release with poetry and I found it quite hard to use, I might go back to `setup.py`.

**Comment by mgorny** [comment]
Hmm, so I guess it's only broken when you're using GitHub snapshots as we have to because pypi sdists don't include tests.
