### ISSUE TITLE
IsDict - Allow ignoring keys

### ISSUE THREAD

**Issue by jd-solanki** [samuelcolvin/dirty-equals#37]
Hi,

I am loving this library 😍 

I am using it to test my FastAPI endpoint and I want to ignore the default columns like `is_active` (also `id`) because I have something like below:

```python
assert [{'id': 1, 'name': 'john'}] == IsList(IsPartialDict(name='john', is_active = True})
```

Certainly, I can use `.settings(ignore={True})` but I fear it might ignore other columns with the value True in the future.

Right now, the above assertion will fail but with `ignore_keys` we will be able to ignore keys safely.

_P.S. I love to make a PR but I checked the source code and I think I shouldn't touch it._

**Comment by osintalex** [comment]
Perhaps I've misunderstood what you're suggesting, but can't you just do this to skip checking `id`?

```python
assert [{'id': 1, 'name': 'john'}] == IsList(IsPartialDict(name='john'))
```

**Comment by samuelcolvin** [comment]
Better to use something like `...id=IsInt` or even `AnyThing`.

But maybe I'm missing what you mean.

**Comment by jd-solanki** [comment]
I am not currently active on that project. For the time being I am closing this issue and try provided solutions. I will reopen it will a detailed description if I am unable to resolve the issue.

Thanks 😊
