### ISSUE TITLE
nan type

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/dirty-equals#54]
Since `float('nan') != float('nan')` we need a custom `FloatNan` type.

**Comment by samuelcolvin** [comment]
inf/-inf too?

**Comment by samuelcolvin** [comment]
definitely still interest, no drawback I know of to `math.isnan`.

I guess we have `FloatNan`, `FloatInfPos`, `FloatInfNeg`?

**Comment by FBruzzesi** [comment]
I would consider a more general `FloatInf` as well (that's the use case it brought me here in the first place).

Just to make sure on naming convention, they should all have a `Is` prefix, correct?

**Comment by samuelcolvin** [comment]
Sorry, yes `Is` prefix.

`FloatInf` is fine by me.

**Comment by alexmojaki** [comment]
This is done, yes?
