### ISSUE TITLE
dirty isinstance

### ISSUE THREAD

**Issue by FBruzzesi** [samuelcolvin/dirty-equals#58]
I find myself using this library more and more and I love it. 
However most of the time I prefer checking instances using `isinstance` built-in over `==`.

This would be possible with the library types by hijacking `__instancecheck__` method both in `DirtyEqualsMeta` and `DirtyEquals` to:

```python
def __instancecheck__(self, other) -> bool:
    return self == other
```

If that is _too dirty_, I could suggest the implementation of an utility function:
```python
def is_instance(value, cls_or_instance):
    return value == cls_or_instance
```

Happy to discuss and eventually work on it!

**Comment by samuelcolvin** [comment]
How would use of `__instancecheck__` work?

**Comment by FBruzzesi** [comment]
`__instancecheck__` is used to override the default behavior of the `isinstance(...)` built-in.

When `isinstance(x, y)` is evaluated, it assumes `y` to be an object, looks for its class and calls `__instancecheck__` on that class, hence `__instancecheck__` should be defined on the type/metaclass of a class. 

However, in this case defining `__instancecheck__` on `DirtyEqualsMeta` alone would not be sufficient for all the checks in _dirty_equals_. Example:
```python
from dirty_equals import IsInt

isinstance(5, IsInt) 
# True
isinstance(5, IsInt(gt=4))
# Error: isinstance() arg 2 must be a type, a tuple of types, or a union
```
In fact `IsInt(gt=4)` is an instance, not a type.
That's the need to implement `__instancecheck__` in `DirtyEquals` class as well (I said it would be dirty, possibly too much!).

(Reference: [datamodel docs](https://docs.python.org/3/reference/datamodel.html#customizing-instance-and-subclass-checks))

**Comment by samuelcolvin** [comment]
I know what it does, my question was about why using it in dorty-equals would be a good idea.

I'm personally not very keen on this, I don't think it helps build declarative tests.

**Comment by FBruzzesi** [comment]
Whooops, My apologies!
Here a minimal, reproducible example/use case:
```python
from dirty_equals import IsPositiveInt
import pytest

class CustomZero:
    value = 0
    
def func(x) -> int | CustomZero:
    return x if x > 0 else CustomZero()

@pytest.mark.parametrize("value, expected", [(1, IsPositiveInt), (-1, CustomZero)]):
def test_func(value, expected):
    assert isinstance(func(value), expected)

# or similarly allows to include both types in instance check
@pytest.mark.parametrize("value", [1, -1]):
def test_func(value):
    assert isinstance(func(value), (IsPositiveInt, CustomZero))
```
More generally, I find it useful for every function that can return a union, with a type implemented in dirty_equals and the other being custom.

**Comment by FBruzzesi** [comment]
Closing as not planned
