### ISSUE TITLE
`IsDataclass` type

### ISSUE THREAD

**Issue by FBruzzesi** [samuelcolvin/dirty-equals#67]
I would be happy to work on `IsDataclass` (related to #3).

Before starting I have a few questions:

- Should it be in the `_other` module?
- Any drawback in using [`dataclasses.is_dataclass`](https://docs.python.org/3/library/dataclasses.html#dataclasses.is_dataclass)?
- I think it would be good to have the option to distinguish between class definition and instance, but glad to get a feedback on this.

**Comment by samuelcolvin** [comment]
Yes please, module up to you.

`dataclasses.is_dataclass` should be fine.

If you want `IsDataClassType` I think that should be a separate type, but you could add it at the same time.

Another question, should `IsDataclass` look at fields, so you can do `IsDataclass(foo=4, bar=5)`? Then do we need `IsPartialDataclass`?

**Comment by samuelcolvin** [comment]
Or `HasAttributes`, still I think it would be a useful addition.

**Comment by FBruzzesi** [comment]
What do you think about the following case:

```py
@dataclass
class Foo:
    a: int
    b: int

foo = Foo(a=1, b=2)

foo == IsDataclass # -> True
foo == IsDataclass(a=1, b=2) # -> True
foo == IsDataclass(a=1) # -> False

foo == IsDataclass() # -> ???
```
