### ISSUE TITLE
Makefile command for testing in local development

### ISSUE THREAD

**Issue by alexmojaki** [samuelcolvin/dirty-equals#83]
I think there should be Makefile command which runs tests with `--update-examples` and without coverage for speed, and this would be the recommended workflow when iterating and testing in local development.

In fact, I think that's what `make test` should be, and the current `test` command (i.e. with coverage and without updating examples) could be renamed to `test:slow` or `ci` or something to indicate that it's the slower version that you run less often to double check things.

**Comment by samuelcolvin** [comment]
I think we recommend [inline-snapshot](https://pypi.org/project/inline-snapshot/) for this kind of thing.
